// Mocks generated by Mockito 5.4.6 from annotations
// in fluxo/test/article_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fluxo/data/services/api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  @override
  String get baseApiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseApiUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseApiUrl),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseApiUrl),
            ),
          )
          as String);

  @override
  set baseApiUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseApiUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<dynamic>> getArticlesWithinCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getArticlesWithinCategory, [category]),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i4.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i4.Future<List<dynamic>>);
}
